# The URL the site will be built for
base_url = "https://ronpopov.me"
title = "Ron Popov"
generate_feeds = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Use terminus theme
theme = "terminus"

[markdown.highlighting]
extra_themes = ["themes/terminus/syntaxes/monokai-classic.json"]
theme = "monokai-classic"

[extra]
# Put all your custom variables here


# Fix icon in "homemenu memory shenanigans part 3" side note box.
[extra.content_security_policy]
allowed_domains = [
    { directive = "img-src", domains = ["'self'", "data:"] },
]

socials = [
    { name = "github", url = "https://github.com/ron-popov" },
    { name = "linkedin", url = "https://www.linkedin.com/in/ron-popov-a3389a228" },
]
