# The URL the site will be built for
base_url = "https://ronpopov.me"
title = "Ron Popov"
generate_feeds = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Use terminus theme
theme = "terminus"

[markdown.highlighting]
theme = "monokai-classic"

[extra]
# Put all your custom variables here
